baseURL: "https://lakshiya.github.io"
languageCode: "en-us"
title: "Priya Lakshmi"
theme: master

Paginate: 3
# disqusShortname: gurusabarish
googleAnalytics: G-3D42J5TFHD
canonifyURLs:  true

markup:
  goldmark:
    renderer:
      unsafe: true

#Menus:
  #main:
    #- identifier: blog
      #name: Blog
      #title: Blog posts
      #url: /blogs
      #weight: 1

    #Dropdown menu
    #- identifier: dropdown
      #title: Example dropdown menu
      #name: Dropdown
      #weight: 2
    #- identifier: dropdown1
      #title: example dropdown 1
      #name: example 1
      #url: /#
      #parent: dropdown
      #weight: 1
    #- identifier: dropdown2
      #title: example dropdown 2
      #name: example 2
      #url: /#
      #parent: dropdown
      #weight: 2

params:
  title: " Portfolio "
  description: Portfolio of Priya Lakshmi Theagarajan
  staticPath: ""  # The path to serve the static files from
  favicon: "Priya_icon.jpg"

  color:

    textColor: "#5453A6"
    secondaryTextColor: "#5453A6"
    backgroundColor: "#F5F5FF"
    primaryColor: "#5453A6"
    secondaryColor: "#E9EBFE"

    darkmode:
      textColor: "#F5F5FF"
      secondaryTextColor: "#F5F5F5"
      backgroundColor: "#484d7e"
      primaryColor: "#F5F5F5"
      secondaryColor: "#565c97"

    # textColor: "#F5F5F5"
    # secondaryTextColor: "#F5F5F5"
    # backgroundColor: "#313552"
    # primaryColor: "#F1E0AC"
    # secondaryColor: "#30475E"

    # darkmode:
    #   textColor: "#2C3333"
    #   secondaryTextColor: "#F5F5F5"
    #   backgroundColor: "#54BAB9"
    #   primaryColor: "#F0F0F0"
    #   secondaryColor: "#78C2C3"

  theme:
    disableThemeToggle: false
    defaultTheme: "light" # dark
    
    # color:  
    #     secondaryBackgroundColor: "Blue"
    #darkmode:
        #secondaryBackgroundColor: "Blue"

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
    

  # If you want to customize the menu, you can change it here
  navbar:
      position: absolute
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hello World! I'm "
    title: "Priya Theagarajan"
    subtitle: "Software Engineer"
    content: "Currently Interning at <a href=https://www.intuitive.com/en-us> <b> Intuitive Surgical Inc</b>. </a>
     With over 4 years of professional experience working in Backend Application development, Cloud Infrastructure, Data engineering, Business analytics and Machine learning projects.  
     I am actively looking for full-time opportunites starting April 2024."
    
    image: "images/Priya_Sec.png"
    button:
      background - color: 
      enable: true
      name: "Resume"
      url: "https://drive.google.com/file/d/1yFjZ9Go-HTS0PMM1Z_5hNkZT2cX2fbA3/view?usp=sharing"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/lakshiya
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/priya-lakshmi-theagarajan/

      #customIcons:
        #- icon: /fav.png
        #  url: "https://example.com"

  # About
  about:
    enable: true
    title: "I'm Open to work from April 2024"
    image: "/images/PriyaID.png"
    content: |-
      A passionate graduate student at the University of Florida, majoring in Computer Science. 
      I live in Mountain View, CA. I love interacting and learning about technologies, I believe that every problem is an opportunity in disguise, and I specialize in crafting software solutions to tackle them.
     
     
    skills:
      enable: true
      title: ""
      items:
        - "<a href="https://www.linux.org/" target="_blank" rel="noreferrer"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/linux/linux-original.svg" alt="linux" width="40" height="40"/> </a>
<a href="https://git-scm.com/" target="_blank" rel="noreferrer"> <img src="https://www.vectorlogo.zone/logos/git-scm/git-scm-icon.svg" alt="git" width="40" height="40"/> </a>
"
        - "Backend development : Node.js, SQL, MongoDB, Oracle DB, MySQL, Django, Flask REST API,"
        - "AWS / Cloud Infrastucture : AWS ECS, IAM, EC2, Lambda, VPN, S3, Cloudformation, SNS, SQS, Serice Catalog, Lakeformation"
        - "Data Engineering / Business Analytics : Python, Spark, Ab Initio, Pandas, Amazon Redshift, AWS Glue, Data Lake, Athena"
        - "DevOps : Linux, Chef, Jenkins, Docker, Terraform"
        - "Machine Learning : Nltk, Pandas, Numpy, Jupyter "
        - "Mentorship, Multi-Cultural Fluency, Team Player"
       
  # Experience
  experience:
    enable: true
    items:      
      - job: "Software Engineer Intern"
        company: "Intuitive Surgical Inc"
        companyUrl: "https://www.intuitive.com/en-us"
        date: "Aug 2023 - Present"
        info:
          enable: true
          content: "Location: Sunnyvale, CA "
        featuredLink:
          enable: false
          url: "https://www.intuitive.com/en-us"
        content: |
          Sunnyvale, California

          - Engineering Applications | <i><b> Tableau, Pandas, Python, REST API, SQL, Windchill, RHEL </b></i>
            - Developed a real-time Enterprise Application license monitoring system by creating an ETL pipeline with Python, Tableau and Hyper table, resulting in cost reduction of over 250K due to removal of unused licenses.
            - Building troubleshooting and monitoring utility using logs from CAD workers with Elasticsearch, Kibana, and Machine learning techniques
            - Deploying IOT Thingworx Foundational and Thingworx Navigate in Redhat Enterprise and SQL server to give stakeholders across an organziation easy access to view Product Life Cycle Management (PLM) data
      
      - job: "Software Engineer"
        company: "University of Florida - College of Medicine"
        companyUrl: "https://med.ufl.edu"
        date: "Feb 2023 - Aug 2023"
        info:
          enable: true
          content: "Location: Gainesville, FL"
        featuredLink:
          enable: false
          url: "https://med.ufl.edu"
        info:
          content:
        content: |-
          Gainesville, Florida

          - Medical Resource Database system | <i><b> Django, Python, PySpark, MySQL, HTML, AWS </b></i>
            - Architected a full-stack inventory database and infrastructure system with Django; streamlined research equipment management and facilitated collaboration between researchers, enhancing resource allocation by 40%
            - Improved application rendering time by 30% through pagination and implementing data transformation pipeline to perform data collection, integration, and data processing on records across departments using PySpark on Oracle data warehouse
            - Applied data modelling and data governance techniques to build database and executed user access control, notification, and application maintenance to ensure consistency in functionality

      - job: "Senior Analyst - Technology"
        company: "Barclays"
        companyUrl: "https://cards.barclaycardus.com"
        date: "Jul 2029 - Aug 2023"
        info:
          enable: true
          content: "Location: Chennai, India"
        featuredLink:
          enable: false
          url: "https://cards.barclaycardus.com"
        info:
          content: 
        content: |-
          Chennai, India
          - Data Lake creation using server-less ETL pipeline on Cloud | <i><b> AWS, Python, CloudFormation, PySpark, Jenkins </b></i>
            - Led data migration of 12 million US Consumer Banking records from Hadoop/Oracle to AWS Data Lake by developing serverless data transformation pipelines resulting in resource conservation of over 50%
            - Enhanced the incident response time by 80% through designing a real-time monitoring and notification systems
            by establishing reconciliation between AWS and on-premises resources using Python and Elasticsearch
            - Reduced the development lifecycle by 30% by building and deploying reusable service catalog products via IaaC
            (Infrastructure as a Code) for AWS services: S3, Lambda, IAM, ECS, Lake formation, SNS, SQS etc.
            - Achieved a 30% cost saving in EC2 server provisioning expenses by implementing adaptive Autoscaling groups
            and Application load balancers to manage traffic based on CPU and memory utilization
            - Provisioned products are utilized to migrate, monitor, and process history and daily batch loads for over 100
            datasets
          - Business Intelligence Dashboard (BI) - Credit Card Fraud Tubemap | <i><b> PL/SQL, Tableau, Visio </b></i>
            - Modularized complex systems involved in Transactional Fraud Customer journey as a Tube map (An E2E
            mapping of customer interactions across fraud detection channels) to visualize data flow and lineage
            - Automated dashboard conceptualized with data visualization software Tableau and SQL queries replaced the
            manual weekly report generated by Fraud Analytics team leading to 80% improvement in report turnaround time

          - Deploy SAS Viya on Cloud | <i><b> AWS, Chef, Terraform, SAS Viya </b></i>
            - Directed efforts for provisioning SAS Viya (Data management platform) on AWS environment with vendors
            - Created Chef cookbook in Ruby with orchestration steps for deployed SAS Viya on AWS EC2
            - Accelerated the efficiency of SAS users to perform complex analytical tasks with improved scalability and performance
          
  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "Master of Science in Computer Science"
        school:
          name: "University of Florida, Florida"
          url: "https://www.eng.ufl.edu/"
        date: "Aug 2022 - April 2024"
        GPA: "3.72 out of 4.0"
        content: |-
            - Worked as a Software Engineer at UF College of Medicine to develop a medical resource inventory system.
            - Was part of the Virtual Experience Research lab to perform user research project on HPV vaccination using virtual humans with Figma.
            - Attending Grace Hopper 2023 Conference.
            - Course Work: Natural Language Processing, Analysis of Algorithms, Computer Architecture, Human Computer Interaction, Advanced Data Structure, Distributed Operating System, Internet Data Streaming.

            Extracurricular Activities
             - Active member of UF WiCSE (Women in Computer Science and Engineering)

      - title: "Bachelor of Engineering in Computer Science and Engineering"
        school:
          name: "SSN College of Engineering, Chennai"
          url: "https://www.ssn.edu.in/"
        date: "Jun 2015 - Apr 2019"
        # GPA: "8.96 out of 10"
        content: |- 
          
          - Computer Science Courses: Cloud Computing, Cryptography and Network Security, Data Structures, Computer Networks, Computer Organization, Compiler Design, Operating Systems, Theory of Computation, Object Oriented Analysis and Design.
          - Data Courses: Database Management Systems, Artificial Intelligence, Data Warehousing and Data Mining, Big Data Analytics.

          Extracurricular Activities
            - Won and participated in multiple Data Structure and SQL events in technical conferences
            - Conducted technical competetion Code Relay in SSNCE Technial Conference Invente 2018
            - Participated in Smart India Hackathon 2018

  #featuredLink:
  #enable: true
  #name: "My academic record"
  #url: "https://example.com"

  # Achievements
  achievements:
    enable: true
    items:
      #- title: Smart India Hackathon 2020
       # content: Won 2nd place in Smart India Hackathon 2020 for developing a Smart Yoga Instructor with feedback using Deep Learning
        #url: "https://www.sih.gov.in"
      
      - title: Barclays Global Recognition Award of Excellence (2020) 
        content: Awarded for delivering one of the most complex customer journey KPI dashboard for Fraud Case Management system.
      - title: Barclays Value Award for Excellence (2021) 
        content: Awarded for leading the AWS Cloud Infrastructure development for the Enterprise Platform team.

      - title: AWS Associate Developer
        content: Certified AWS Developer with hand-on experience in implementing CI/CD pipeline and AWS services such as ElasticBeanstalk, ECS, ECR, CloudFormation, Glue & Step Function etc.
        image: /images/projects/AWSDev.png
        url: https://www.credly.com/badges/8552240b-8991-4658-a69d-1d6d2f28dd8f?source=linked_in_profile
        
      - title: Certified Linux and RHEL Developer
        content: Completed courses - Fundamentals of Red Hat Enterprise Linux, Hands-on Introduction to Linux Commands and Shell and Learning Linux for LFCA Certification
        image: /images/projects/AWSDev.png
        url: https://www.coursera.org/account/accomplishments/verify/FNL2B8Y4FHDQ?utm_source=link&utm_medium=certificate&utm_content=cert_image&utm_campaign=pdf_header_button&utm_product=course


  # projects
  projects:
    enable: true
    items:
      - title: Social Media web application using MERN Stack
        content: Socio is a simple social media app that allows users to post interesting events that happened in their lives, It is a Full stack application using React, Node.js, Express & MongoDB.
        image: /images/projects/Socio-Full-new.png
        featured:
          name: Click here to know more!
          link: https://github.com/lakshiya/social-media-webapp
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          #- icon: fa fa-envelope
          #  url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/lakshiya/social-media-webapp
          # - icon: fab fa-twitter
          #  url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Mental Health analytics on Reddit Posts using NLP Topic Modelling
        content: Using NLP-based Topic Modeling techniques to discover correlations between Lifestyle Habits and Mental Health Concerns using data from subreddits like /depression, /parenting, /anxiety, /fitness etc.
        image: /images/projects/NLP-Project.png
        featured:
          name: Click here to know more!
          link: https://docs.google.com/presentation/d/1ShW_uTYcuRiGpgzbf9K9FK6delz2iSgHsXO_K6Dfwbk/edit?usp=sharing
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/aishwaryasharmaccoew/CIS6930-NLP

      - title: Event Management system - BookMyEvents
        content: Book My Events is a simple events management application built using Django for creating, booking and managing student organization events. 
        image: /images/projects/HCI-Events.png
        featured:
          name: Click here to know more!
          link: https://docs.google.com/presentation/d/1K7CvGTUQsXhiPyEIHKpCQteA6glh0e3PDMkkyQjoRE8/edit?usp=sharing
        # badges:
        #   - "Django"
        #   - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/lakshiya/HCI_Django/tree/main



  #Contact
  contact:
    enable: true
    content: My inbox is always open. Whether you have a question or just want to say hi, Drop me a message !
    email: priya.theagarajan12@gmail.com
    btnName: Get in Touch

  footer:
    recentPosts: false
    socialNetworks:
      github: https://github.com/lakshiya
      linkedin: https://www.linkedin.com/in/priya-lakshmi-theagarajan/
    # twitter: https://twitter.com
      # instagram: https://www.instagram.com/riya_laksh/
    # facebook: https://facebook.com
